# Generated by Django 5.0 on 2024-11-14 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('endereco', models.CharField(max_length=120)),
                ('bairro', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=120)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pessoa')),
            ],
        ),
    ]
